name: Update Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: safwannuddin
          svg_out_path: ./output/github-snake-dark.svg
          svg_out_path_dark: ./output/github-snake-dark.svg
          gif_out_path: ./output/github-snake.gif
          gif_out_path_dark: ./output/github-snake-dark.gif
          svg_include_commit: true
          svg_include_commit_dark: true
          svg_include_commit_message: true
          svg_include_commit_message_dark: true
          svg_include_commit_emoji: true
          svg_include_commit_emoji_dark: true
          svg_include_commit_author: true
          svg_include_commit_author_dark: true
          svg_include_commit_date: true
          svg_include_commit_date_dark: true
          svg_include_commit_count: true
          svg_include_commit_count_dark: true
          svg_include_commit_emoji_count: true
          svg_include_commit_emoji_count_dark: true
          svg_include_commit_emoji_percentage: true
          svg_include_commit_emoji_percentage_dark: true

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
